// TODO remove this file
window._env_ = {
  REACT_APP_SENTRY_ENV: "local",
  PUBLIC_URL: "https://static.devfdg.net/uc/v3",
  REACT_APP_STATIC_HOST: "https://static.devfdg.net",
  REACT_APP_API_PROXY_HOST: "https://www.devfdg.net",
  REACT_APP_SENTRY_DSN: "https://7a1c383ff0f74eea8f8ba8ac590fff90@report.binance.gg/26",
  REACT_APP_INMAIL_WSSURL_TEMPLATE: "wss://bstream.devfdg.net:9443",
  REACT_APP_RAVE_URL: "https://api.ravepay.co",
  REACT_APP_ADVCASH_PATH: "https://wallet.advcash.com/sci",
  REACT_APP_EPAY_HOST: "http://19291v583z.imwork.net:54936",
  REACT_APP_C2C_HOST_TEMPLATE: "https://c2c.fe.devfdg.net",
  REACT_APP_CHECKOUT_PUBLIC_KEY: "pk_test_ffc5fcb5-68b3-4eeb-91ab-a28e90902cca",
  REACT_APP_C2C_ADMIN_HOST_TEMPLATE: "https://c2c-admin.fe.devfdg.net",
  REACT_APP_ETANA_LINK_URL: "https://sandbox.beta.etana.com",
  REACT_APP_SITE_HOST: "https://www.devfdg.net",
  ACCELERATE_DEFAULT_DOMAIN: "api.yshyqxx.com",
  ACCELERATE_AVAILABLE_DOMAIN: "api.yshyqxx.com,api.hanqiweb.cloud",
  ACCELERATE_ENABLED_SITES: "www.binancezh.com,www.binancezh.net",
  SENSORS_SERVER_HOST: "default",
  ACCOUNTS_PREFIX: "accounts",
  SIFT_ACCOUNT: "913800117a",
  SYBE_ORG_ID: "45ssiuz3",
  MARGIN_STREAM_HOST_TEMPLATE: "wss://margin-stream.binance.com:9443",
  TRADE_STREAM_HOST_TEMPLATE: "wss://www.devfdg.net:9443",
  RECAPTCHA_KEY: "6Lei0OgUAAAAALr0kUiepNP8V-4l3PTA8uyNdMRo",
  MARKET_STREAM_HOST: "ws://172.21.43.67:9443",
  API_HOST: "https://www.devfdg.net",
  GTM_TRACKING_ID: "WW2RRZX",
  GA_TRACKING_ID: "test",
}
