require('plugins')
require('mappings')
require('nvim-tree-config')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
vim.cmd('set nu')
vim.cmd('colorscheme onedark')
